### ISSUE TITLE
Support discovering USB HID devices on linux

### ISSUE THREAD

**Issue by marshallbrekka** [marshallbrekka/go-u2fhost#1]
Use this firefox extension as a reference.

https://github.com/prefiks/u2f4moz/blob/master/c_src/libu2f-host/devs.c#L117-L142

**Comment by VictorDenisov** [comment]
I'm trying to use this library on linux, but it filters out my keys due to this line: https://github.com/marshallbrekka/go-u2fhost/blob/master/hid/hid.go#L46
If you look at the doc for UsagePage and Usage you can see that those values are only for mac and windows. On linux they are zeroes. Why are you using those values?

**Comment by marshallbrekka** [comment]
@VictorDenisov this has been long on my personal backlog of issues to resolve.
I'd love some help on this, as it appears the solve exists outside the context of just this project.

# Short answer: 
usage and usage page are available on linux, but they are not accessible given the current way that [hidapi](https://github.com/signal11/hidapi) uses [libusb](https://github.com/signal11/hidapi/blob/a6a622ffb680c55da0de787ff93b80280498330f/libusb/hid.c#L129-L135).

# Longer Answer
I had done some research a while ago, but can't seem to find it, so sorry if my notes are a little sparse, or not as correct as they should be.

libusb currently has the [code disabled](https://github.com/signal11/hidapi/blob/a6a622ffb680c55da0de787ff93b80280498330f/libusb/hid.c#L129-L135) for [grabbing the full usage page.](https://github.com/signal11/hidapi/blob/a6a622ffb680c55da0de787ff93b80280498330f/libusb/hid.c#L595-L612) This is probably a fine choice as most users may not need it. In our case it would be ideal to be able to access it when needed to validate the device is u2f compatible.

There is another usability issue. The [karalabe/hid](https://github.com/karalabe/hid) project chooses to use the [libusb](https://github.com/karalabe/hid/blob/9c14560f9ee858c43f40b5cd01392b167aacf4e8/hid_enabled.go#L36) backend on linux, as opposed to the `hidraw` backend.
As far as I remember, the hidraw backend could interact with the u2f devices without any special permissions, but the libusb backend required the end user to add [udev rules](https://github.com/Yubico/libu2f-host/blob/master/70-u2f.rules).

Fortunately we can look at what Firefox has done, via their rust library.

I'm not 100% sure what the best path is to move forward, as it seems some decent changes would be required outside of this project. 

- Linux: [hidraw](https://github.com/mozilla/authenticator-rs/blob/fb6bb17a135b2d897adebac80ac378f53eb73028/src/linux/hidraw.rs#L50-L65)
- FreeBSD: [uhid](https://github.com/mozilla/authenticator-rs/blob/bd1f86042c9f7fc29a75b489d767ff431a805836/src/freebsd/uhid.rs#L74-L88)

# Can the usage page check just be removed entirely?
Honestly I'm not sure what kind of dangers might arise by issuing commands to non-u2f devices. I'd be very open to exploring that if you have the bandwidth to do that research.

**Comment by VictorDenisov** [comment]
Thanks for your reply. I'll be looking into this problem as it's a more or less pressing issue for me. Though it looks like if I want a tool that works just for me I can just do the custom build of the tool that is using your library.

**Comment by marshallbrekka** [comment]
Also looks like there is some progress on making it more accessible on linux https://github.com/libusb/hidapi/pull/139
